name: Create and publish a Docker image

on:
  push: # PUSH & PR merge 될 경우
    branches: ["juya"] # juya branch 로 push 발생할 경우
  # workflow trigger button
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # 가장 최신 image 에 latest tag 달기
#          flavor: |
#            latest=true
          # Git short commit, use git version tag
          tags: |
            type=sha
            type=semver,pattern={{version}}
     

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile # repository 기준 도커파일 위치
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      ##### clone
      - name : clone config repo
        run : |
           git clone https://${{ secrets.USE_REPO }}@github.com/juyoung810/slack-bot-config
           cd slack-bot-config

      - name: Change config repo values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq '.spec.template.spec.containers.[0].image = ${{ steps.meta.outputs.tags }}' ajae_deployment.yaml

      - name: push to config repo
        run: |
          git checkout -b ${{ github.actor }}-${{ steps.meta.outputs.tags }}
          git add .
          git commit -m "Change Image version"
          git remote -v
          
          git push --set-upstream origin ${{ github.actor }}-${{ steps.meta.outputs.tags }}
          git push --set-upstream https://${{ secrets.GITHUB_TOKEN }}@github.com/juyoung810/slack-bot-config ${{ github.actor }}-${{ steps.meta.outputs.tags }}
